version: '2'
services:
    deepak_micro-app:
        image: deepak_micro
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://deepak_micro-mysql:3306/deepak_micro?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    deepak_micro-mysql:
        extends:
            file: mysql.yml
            service: deepak_micro-mysql
